kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: propschain-metrics-pvc
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
