apiVersion: v1
kind: PersistentVolume
metadata:
  name: propschain-metrics-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-025191e9a7775c4a9
