kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sawtooth-metrics-pvc
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      Environment: production
      Service: sawtooth-metrics
    matchExpressions:
      - { key: Environment, operator: In, values: [production] }
