apiVersion: v1
kind: PersistentVolume
metadata:
  name: sawtooth-metrics-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: sawtooth-metrics-pvc
    namespace: default
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0324532b9d24ef31f