apiVersion: v1
kind: PersistentVolume
metadata:
  name: sawtooth-metrics-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0276a8191c0cb0198