kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: validator1
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard
