apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: validator1
    namespace: default
  storageClassName: standard
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-030bd50e256432b43
