apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: state-api
  namespace: default
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: state-api
  targetCPUUtilizationPercentage: 70
