kind: Service
apiVersion: v1
metadata:
  name: sawtooth-validator
  annotations:
    dns.alpha.kubernetes.io/external: "validator.staging.sidechain.propsproject.io"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "90"
spec:
  type: LoadBalancer
  selector:
    app: sawtooth-validator
  ports:
    - name: "4004"
      protocol: TCP
      port: 4004
      targetPort: 4004
    - name: "8800"
      protocol: TCP
      port: 8800
      targetPort: 8800
    - name: "5050"
      protocol: TCP
      port: 5050
      targetPort: 5050
  loadBalancerSourceRanges:
    - "34.198.32.89/32"
    - "10.0.0.0/16"
    - "3.87.177.84/32"
    - "52.202.115.169/32"
    - "18.210.158.1/32"