apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pending-props-tp
  namespace: default
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: pending-props-tp
  targetCPUUtilizationPercentage: 70
