apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-props-tp
  labels:
    app: pending-props-tp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pending-props-tp
  template:
    metadata:
      labels:
        app: pending-props-tp
    spec:
      containers:
        - name: pending-props-tp
          image: 774122189772.dkr.ecr.us-east-1.amazonaws.com/pending-props-tp-staging-sidechain
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: global-secrets
            - configMapRef:
                name: pending-props-tp
            - configMapRef:
                name: general-config
          env:
          - name: NAME
            value: "pending-props-tp"
          command:
            - sh
          args:
            - -c
            - "./build/bin/pending-props-tp -c -f ./configs/default.json"
