apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: props-eth-sync-api
  namespace: default
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: props-eth-sync-api
  targetCPUUtilizationPercentage: 70
