apiVersion: apps/v1
kind: Deployment
metadata:
  name: sawtooth-intkey-tp-python
  labels:
    app: sawtooth-intkey-tp-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sawtooth-intkey-tp-python
  template:
    metadata:
      labels:
        app: sawtooth-intkey-tp-python
    spec:
      containers:
        - name: sawtooth-intkey-tp-python
          image: hyperledger/sawtooth-intkey-tp-python:1.1
          command:
            - bash
          args:
            - -c
            - "intkey-tp-python -vv -C tcp://sawtooth-validator:4004"
