apiVersion: apps/v1
kind: Deployment
metadata:
  name: sawtooth-devmode-engine
  labels:
    app: sawtooth-devmode-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sawtooth-devmode-engine
  template:
    metadata:
      labels:
        app: sawtooth-devmode-engine
    spec:
      containers:
        - name: sawtooth-devmode-engine
          image: hyperledger/sawtooth-devmode-engine-rust:1.1.5
          command:
            - bash
          args:
            - -c
            - "devmode-engine-rust -C tcp://sawtooth-validator:5050"
          envFrom:
            - configMapRef:
                name: general-config
