apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sawtooth-shell
  labels:
    app: sawtooth-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sawtooth-shell
  template:
    metadata:
      labels:
        app: sawtooth-shell
    spec:
      containers:
        - name: sawtooth-shell
          image: hyperledger/sawtooth-shell:1.1.5
          command:
            - bash
          args:
            - -c
            - "sawtooth keygen && tail -f /dev/null"
