apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-es-v1.20
  namespace: kube-system
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    version: v1.20
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-es
        kubernetes.io/cluster-service: "true"
        version: v1.20
    spec:
      containers:
      - name: fluentd-es
        image: younow/kubernetes-fluentd-loggly:1.0.1
        imagePullPolicy: Always
        command:
          - '/bin/sh'
          - '-c'
          - '/usr/sbin/td-agent 2>&1 >> /var/log/fluentd.log'
        env:
          - name: LOGGLY_URL
            valueFrom:
              secretKeyRef:
                key: LOGGLY_URL
                name: addons-secrets
          - name: LOG_LEVEL
            value: "info"
          - name: BUFFER_CHUNK_LIMIT
            value: "2M"
          - name: BUFFER_QUEUE_LIMIT
            value: "32"
          - name: FLUSH_INTERVAL
            value: "5s"
          - name: MAX_RETRY_WAIT
            value: "31"
          - name: NUM_THREADS
            value: "8"
          - name: KEEPALIVE_TIMEOUT
            value: "60"
        resources:
          limits:
            memory: 400Mi
            cpu: 400m
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      # nodeSelector:
      #   alpha.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 4
