apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-transfers
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            nodetier: "1"
          restartPolicy: OnFailure
          containers:
          - name: sync-transfers
            image: 774122189772.dkr.ecr.us-east-1.amazonaws.com/props-eth-sync-staging-sidechain:30
            command:
              - bash
            args:
              - -c
              - "npm run sync-latest"
            imagePullPolicy: IfNotPresent
            env:
              - name: SERVICE_NAME
                value: "api"
              - name: DOGSTATSD_HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            envFrom:
              - secretRef:
                  name: props-eth-sync-secrets
              - secretRef:
                  name: global-secrets
              - configMapRef:
                  name: props-eth-sync
              - configMapRef:
                  name: general-config
