apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sawtooth-restapi
  labels:
    app: sawtooth-restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sawtooth-restapi
  template:
    metadata:
      labels:
        app: sawtooth-restapi
    spec:
      containers:
        - name: sawtooth-rest-api
          image: hyperledger/sawtooth-rest-api:1.0
          ports:
            - name: api
              containerPort: 8008
          command:
            - bash
          args:
            - -c
            - "echo ${OPENTSDB_USERNAME} >> /etc/sawtooth/rest_api.toml && \
               echo ${OPENTSDB_PW} >> /etc/sawtooth/rest_api.toml && \
               sawtooth-rest-api -C tcp://sawtooth-validator:4004 \
               --bind 0.0.0.0:8008"