apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: propschain-tp
  labels:
    app: propschain-tp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: propschain-tp
  template:
    metadata:
      labels:
        app: propschain-tp
    spec:
      nodeSelector:
        nodetier: "1"
      containers:
        - name: propschain-tp
          image: 774122189772.dkr.ecr.us-east-1.amazonaws.com/pending-props-tp-production-sidechain
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: global-secrets
            - configMapRef:
                name: propschain-general-config
          env:
          - name: NAME
            value: "propschain-tp"
          command:
            - sh
          args:
            - -c
            - "/go/bin/pending-props-tp -c -f /go/bin/configs/default.json"
