apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: propschain-tp
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 4
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: propschain-tp
  targetCPUUtilizationPercentage: 70
