---
apiVersion: v1
data:
  START_UP_SCRIPT: "https://raw.githubusercontent.com/propsproject/sidechain-kubernetes/master/production/scripts/sawtooth-validator/validator.sh"
kind: ConfigMap
metadata:
  name: sawtooth-validator
