apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sawtooth-validator
  labels:
    app: sawtooth-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sawtooth-validator
  template:
    metadata:
      labels:
        app: sawtooth-validator
    spec:
      nodeSelector:
        nodetier: "1"
      containers:
        - name: sawtooth-validator
          image: hyperledger/sawtooth-validator:1.1.2
          ports:
            - name: tp
              containerPort: 4004

            - name: consensus
              containerPort: 5050

            - name: validators
              containerPort: 8800
          command:
            - bash
          args:
            - -c
            - "apt-get update && apt-get -y install curl && curl -s ${START_UP_SCRIPT_POET} | bash"
          envFrom:
            - configMapRef:
                name: sawtooth-validator
            - configMapRef:
                name: general-config
            - secretRef:
                name: validator-secrets
          env:
            - name: OPENTSDB_PW
              valueFrom:
                secretKeyRef:
                    key: OPENTSDB_PW
                    name: global-secrets
            - name: SAWTOOTH_HOME
              value: "/opt/sawtooth"
          volumeMounts:
            - name: sawtooth-validator
              mountPath: "/opt"
            - name: poet-shared-0
              mountPath: "/poet-shared"
      volumes:
        - name: sawtooth-validator
          persistentVolumeClaim:
            claimName: validator1
        - name: poet-shared-0
          emptyDir: {}
