apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: validator1
    namespace: default
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-03dcde207074e1057
