apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eth-sync
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: props-eth-sync-api
              image: 774122189772.dkr.ecr.us-east-1.amazonaws.com/props-eth-sync-staging-sidechain:22
              imagePullPolicy: IfNotPresent
              env:
                - name: SERVICE_NAME
                  value: "api"
                - name: DOGSTATSD_HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              envFrom:
                - secretRef:
                    name: props-eth-sync-secrets
                - secretRef:
                    name: global-secrets
                - configMapRef:
                    name: props-eth-sync
                - configMapRef:
                    name: general-config
