kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: propschain-validator-claim
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
