apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: eth-sync-tp
  labels:
    app: eth-sync-tp
spec:
  selector:
    matchLabels:
      app: eth-sync-tp
  template:
    metadata:
      labels:
        app: eth-sync-tp
    spec:
      nodeSelector:
        nodetier: "1"

      restartPolicy: Never
      containers:
        - name: sync-transfers
          image: 774122189772.dkr.ecr.us-east-1.amazonaws.com/props-eth-sync-production-sidechain:34
          command:
            - bash
          args:
            - -c
            - "npm run sync-latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "api"
            - name: DOGSTATSD_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - secretRef:
                name: props-eth-sync-secrets
            - secretRef:
                name: global-secrets
            - configMapRef:
                name: props-eth-sync
            - configMapRef:
                name: general-config
