apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: propschain-restapi
  labels:
    app: propschain-restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: propschain-restapi
  template:
    metadata:
      labels:
        app: propschain-restapi
    spec:
      nodeSelector:
        nodetier: "1"
      containers:
        - name: propschain-restapi
          image: hyperledger/sawtooth-rest-api:1.2.2
          ports:
            - name: api
              containerPort: 8008
          envFrom:
            - configMapRef:
                name: propschain-general-config
          env:
            - name: OPENTSDB_PW
              valueFrom:
                secretKeyRef:
                  key: OPENTSDB_PW
                  name: global-secrets
          command:
            - "/bin/bash"
            - "-ec"
            - |
              echo "opentsdb_username = \"${OPENTSDB_USERNAME}\"" >> /etc/sawtooth/rest_api.toml
              echo "opentsdb_password = \"${OPENTSDB_PW}\"" >> /etc/sawtooth/rest_api.toml
              sawtooth-rest-api -C tcp://propschain-validator:4004 --opentsdb-url ${OPENTSDB_URL} --opentsdb-db ${OPENTSDB_DB} --bind 0.0.0.0:8008
