kind: Service
apiVersion: v1
metadata:
  name: propschain-restapi
  annotations:
    dns.alpha.kubernetes.io/external: "api.propschain.propsproject.io"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:774122189772:certificate/c96af1a8-cc58-4e3f-bf8b-b5d9790250dd"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
spec:
  type: LoadBalancer
  selector:
    app: propschain-restapi
  ports:
    - name: "8008"
      protocol: TCP
      port: 443
      targetPort: 8008
    - name: "8008-internal"
      protocol: TCP
      port: 8008
      targetPort: 8008
  loadBalancerSourceRanges:
    - "52.45.197.180/32"
    - "52.45.115.108/32"
    - "35.174.190.243/32"
    - "10.3.0.0/16"
    - "34.198.32.89/32"
