apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sawtooth-poet
  labels:
    app: sawtooth-poet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sawtooth-poet
  template:
    metadata:
      labels:
        app: sawtooth-poet
    spec:
      containers:
        - name: sawtooth-poet-validator-registry-tp
          image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
          command:
            - bash
          args:
            - -c
            - "poet-validator-registry-tp -vv -C tcp://sawtooth-validator:4004"