kind: Service
apiVersion: v1
metadata:
  name: sawtooth-poet
spec:
  type: NodePort
  selector:
    app: sawtooth-poet
  ports:
    - name: "5050"
      protocol: TCP
      port: 5050
      targetPort: 5050