apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sawtooth-validator
  namespace: default
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sawtooth-validator
  targetCPUUtilizationPercentage: 70
