kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sawtooth-poet-engine-disk
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi